### PR TITLE
Add kubernetes clusters

### LINKED ISSUE #16: Feature: Add ability to create a Kubernetes Cluster on DigitalOcean
### What problem are you facing?

I would like the ability to create a Kubernetes Cluster using resource definitions with Crossplane.

You can view the API reference [here](https://docs.digitalocean.com/reference/api/api-reference/#operation/create_kubernetes_cluster), and you can also find the godo documentation [here](https://pkg.go.dev/github.com/digitalocean/godo#KubernetesClusterCreateRequest).

### PR DESCRIPTION
**Pull request by ADustyOldMuffin**
Closes #16 

Adds the ability to create Kubernetes Clusters on DigitalOcean, and updates the observed state.

### CODE REVIEW

**Comment by samueltorres** [comment]
What's missing on this provider ? :)

**Comment by ADustyOldMuffin** [comment]
> What's missing on this provider ? :) 

Hello! You can check our issues and see what's left.

**Comment by tillepille** [comment]
Maybe I am blind but I don't see any unchecked point on the issue.

**Comment by samueltorres** [comment]
I asked the wrong question :( Sorry 
My question was mostly on what are the things that are missing on this PR to get merged :)

**Comment by ADustyOldMuffin** [comment]
Nothing! It should be good to go, just waiting on a review.

**Comment by kimschles** [comment]
I was able to create a DOKS cluster from a KIND cluster using the `k8s-cluster.yaml manifest`. Good work, @ADustyOldMuffin! I'll let you do the honor of merging the PR.

**Review by kimschles — APPROVED** [review]
This works as expected. 🥳

**Pull request merged**
